[debug]
DEBUG = 1

[network]
IP = '127.0.0.1'
OUT_PORT = 7000
IN_PORT = 8000

[buttons]
    [buttons.b0]
        PINS = [3, 5]
        ADDRESS = "/rotary_0"
    [buttons.b1]
        PINS = [8, 10]
        ADDRESS = "/rotary_1"
    [buttons.b2]
        PINS = [23, 24]
        ADDRESS = "/rotary_2"

[i2c]
CLK = 13
DIO = 11
